"""add wallet top-ups transfers subscriptions

Revision ID: a1635064cfed
Revises: 45b59812084d
Create Date: 2026-10-09 21:30:07.244706+00:00

"""

from typing import Sequence, Union

from alembic import op
import json

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a1635064cfed"
down_revision: Union[str, Sequence[str], None] = "45b59812084d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    for value in ("top_up", "transfer_in", "transfer_out", "subscription_fee", "adjustment"):
        op.execute(f"ALTER TYPE wallet_entry_kind ADD VALUE IF NOT EXISTS '{value}'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fee_schedules",
        sa.Column("effective_month", sa.Date(), nullable=False),
        sa.Column("tiers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_fee_schedules_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fee_schedules")),
        sa.UniqueConstraint("effective_month", name=op.f("uq_fee_schedules_effective_month")),
    )
    op.create_table(
        "subscription_charges",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("earnings", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("fee", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "status", sa.Enum("paid", "pending", "waived", name="charge_status"), nullable=False
        ),
        sa.Column("free_period", sa.Boolean(), nullable=False),
        sa.Column("schedule_id", sa.Uuid(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("entry_id", sa.Uuid(), nullable=True),
        sa.Column("waived_reason", sa.String(length=500), nullable=True),
        sa.Column("waived_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "notified_due_soon", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "notified_overdue", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["wallet_entries.id"],
            name=op.f("fk_subscription_charges_entry_id_wallet_entries"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["fee_schedules.id"],
            name=op.f("fk_subscription_charges_schedule_id_fee_schedules"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_subscription_charges_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["waived_by_id"],
            ["users.id"],
            name=op.f("fk_subscription_charges_waived_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_charges")),
        sa.UniqueConstraint("user_id", "month", name=op.f("uq_subscription_charges_user_id")),
    )
    op.create_index(
        op.f("ix_subscription_charges_month"), "subscription_charges", ["month"], unique=False
    )
    op.create_index(
        "ix_subscription_charges_status_due",
        "subscription_charges",
        ["status", "due_at"],
        unique=False,
    )
    op.create_table(
        "wallet_top_ups",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "completed", "rejected", "unmatched", name="top_up_status"),
            nullable=False,
        ),
        sa.Column("method", sa.Enum("binance_pay", name="top_up_method"), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("reference", sa.String(length=64), nullable=True),
        sa.Column("transaction_id", sa.String(length=64), nullable=True),
        sa.Column("payer_binance_id", sa.String(length=20), nullable=True),
        sa.Column("payer_name", sa.String(length=120), nullable=True),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("rejection_reason", sa.String(length=500), nullable=True),
        sa.Column("entry_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_by_id", sa.Uuid(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["wallet_entries.id"],
            name=op.f("fk_wallet_top_ups_entry_id_wallet_entries"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["users.id"],
            name=op.f("fk_wallet_top_ups_reviewed_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_wallet_top_ups_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallet_top_ups")),
        sa.UniqueConstraint("transaction_id", name=op.f("uq_wallet_top_ups_transaction_id")),
    )
    op.create_index(op.f("ix_wallet_top_ups_status"), "wallet_top_ups", ["status"], unique=False)
    op.create_index(
        "ix_wallet_top_ups_user_status", "wallet_top_ups", ["user_id", "status"], unique=False
    )
    op.add_column("wallet_entries", sa.Column("counterpart_user_id", sa.Uuid(), nullable=True))
    op.add_column("wallet_entries", sa.Column("created_by_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_wallet_entries_counterpart_user_id"),
        "wallet_entries",
        ["counterpart_user_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_wallet_entries_created_by_id_users"),
        "wallet_entries",
        "users",
        ["created_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_wallet_entries_counterpart_user_id_users"),
        "wallet_entries",
        "users",
        ["counterpart_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("wallets", sa.Column("binance_pay_id", sa.String(length=20), nullable=True))
    op.create_unique_constraint(op.f("uq_wallets_binance_pay_id"), "wallets", ["binance_pay_id"])
    # ### end Alembic commands ###
    # Fee tiers approved by Carlos (docs/product/business-model.md), editable from the admin.
    tiers = [
        {"above": above, "fee": fee}
        for above, fee in (
            ("0.00", "0.00"),
            ("100.00", "5.00"),
            ("200.00", "10.00"),
            ("300.00", "15.00"),
            ("400.00", "20.00"),
            ("500.00", "25.00"),
            ("600.00", "30.00"),
        )
    ]
    op.execute(
        sa.text(
            "INSERT INTO fee_schedules (id, effective_month, tiers, created_at, updated_at) "
            "VALUES (gen_random_uuid(), '2026-01-01', CAST(:tiers AS jsonb), now(), now())"
        ).bindparams(tiers=json.dumps(tiers))
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_wallets_binance_pay_id"), "wallets", type_="unique")
    op.drop_column("wallets", "binance_pay_id")
    op.drop_constraint(
        op.f("fk_wallet_entries_counterpart_user_id_users"), "wallet_entries", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_wallet_entries_created_by_id_users"), "wallet_entries", type_="foreignkey"
    )
    op.drop_index(op.f("ix_wallet_entries_counterpart_user_id"), table_name="wallet_entries")
    op.drop_column("wallet_entries", "created_by_id")
    op.drop_column("wallet_entries", "counterpart_user_id")
    op.drop_index("ix_wallet_top_ups_user_status", table_name="wallet_top_ups")
    op.drop_index(op.f("ix_wallet_top_ups_status"), table_name="wallet_top_ups")
    op.drop_table("wallet_top_ups")
    op.drop_index("ix_subscription_charges_status_due", table_name="subscription_charges")
    op.drop_index(op.f("ix_subscription_charges_month"), table_name="subscription_charges")
    op.drop_table("subscription_charges")
    op.drop_table("fee_schedules")
    # ### end Alembic commands ###
    for name in ("charge_status", "top_up_status", "top_up_method"):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
    # Postgres cannot drop enum values; the extra wallet_entry_kind values stay (unused).
