"""add config and drivers

Revision ID: d58536282b54
Revises: 5290c5bae6e2
Create Date: 2026-10-09 18:00:17.039492+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d58536282b54"
down_revision: Union[str, Sequence[str], None] = "5290c5bae6e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_settings")),
        sa.UniqueConstraint("key", name=op.f("uq_app_settings_key")),
    )
    op.create_table(
        "driver_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft", "pending_review", "approved", "rejected", "suspended", name="driver_status"
            ),
            nullable=False,
        ),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("national_id", sa.String(length=20), nullable=False),
        sa.Column("rif", sa.String(length=20), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("city", sa.String(length=32), nullable=False),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by_id", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_trip_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["users.id"],
            name=op.f("fk_driver_profiles_reviewed_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_driver_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_driver_profiles")),
        sa.UniqueConstraint("national_id", name=op.f("uq_driver_profiles_national_id")),
        sa.UniqueConstraint("user_id", name=op.f("uq_driver_profiles_user_id")),
    )
    op.create_index(op.f("ix_driver_profiles_status"), "driver_profiles", ["status"], unique=False)
    op.create_table(
        "driver_documents",
        sa.Column("driver_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "id_card",
                "rif",
                "drivers_license",
                "medical_certificate",
                "vehicle_registration",
                "selfie",
                "vehicle_photo",
                name="driver_document_kind",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", name="driver_document_status"),
            nullable=False,
        ),
        sa.Column("key", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("reviewed_by_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["driver_profiles.id"],
            name=op.f("fk_driver_documents_driver_id_driver_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["users.id"],
            name=op.f("fk_driver_documents_reviewed_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_driver_documents")),
        sa.UniqueConstraint("key", name=op.f("uq_driver_documents_key")),
    )
    op.create_index(
        op.f("ix_driver_documents_driver_id"), "driver_documents", ["driver_id"], unique=False
    )
    op.create_table(
        "vehicles",
        sa.Column("driver_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Enum("moto", "car", name="vehicle_type"), nullable=False),
        sa.Column("brand", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=50), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("plate", sa.String(length=12), nullable=False),
        sa.Column("color", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["driver_profiles.id"],
            name=op.f("fk_vehicles_driver_id_driver_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicles")),
        sa.UniqueConstraint("driver_id", name=op.f("uq_vehicles_driver_id")),
        sa.UniqueConstraint("plate", name=op.f("uq_vehicles_plate")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vehicles")
    op.drop_index(op.f("ix_driver_documents_driver_id"), table_name="driver_documents")
    op.drop_table("driver_documents")
    op.drop_index(op.f("ix_driver_profiles_status"), table_name="driver_profiles")
    op.drop_table("driver_profiles")
    op.drop_table("app_settings")
    sa.Enum(name="driver_document_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="driver_document_kind").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="vehicle_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="driver_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
