"""add rates promotions wallet

Revision ID: 45b59812084d
Revises: a6c070a172af
Create Date: 2026-10-09 20:35:32.727133+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "45b59812084d"
down_revision: Union[str, Sequence[str], None] = "a6c070a172af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchange_rates",
        sa.Column("source", sa.Enum("bcv", "binance", name="rate_source"), nullable=False),
        sa.Column("rate", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("origin", sa.Enum("auto", "manual", name="rate_origin"), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_exchange_rates_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exchange_rates")),
    )
    op.create_index(
        "ix_exchange_rates_source_fetched", "exchange_rates", ["source", "fetched_at"], unique=False
    )
    op.create_table(
        "promotions",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("code", sa.String(length=20), nullable=True),
        sa.Column(
            "discount_type", sa.Enum("percent", "fixed", name="discount_type"), nullable=False
        ),
        sa.Column("discount_value", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("max_discount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("min_fare", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("budget", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("max_uses_per_passenger", sa.Integer(), nullable=False),
        sa.Column("max_total_uses", sa.Integer(), nullable=True),
        sa.Column("first_ride_only", sa.Boolean(), nullable=False),
        sa.Column("service_areas", postgresql.ARRAY(sa.String(length=60)), nullable=False),
        sa.Column("vehicle_types", postgresql.ARRAY(sa.String(length=16)), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("budget > 0", name=op.f("ck_promotions_budget_positive")),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_promotions_dates_ordered")),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_promotions_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promotions")),
    )
    op.create_index(
        "uq_promotions_code",
        "promotions",
        ["code"],
        unique=True,
        postgresql_where=sa.text("code IS NOT NULL"),
    )
    op.create_table(
        "wallets",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "balance",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("balance >= 0", name=op.f("ck_wallets_balance_not_negative")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_wallets_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallets")),
        sa.UniqueConstraint("user_id", name=op.f("uq_wallets_user_id")),
    )
    op.create_table(
        "wallet_entries",
        sa.Column("wallet_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Enum("promo_credit", name="wallet_entry_kind"), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("ride_id", sa.Uuid(), nullable=True),
        sa.Column("promotion_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["promotion_id"],
            ["promotions.id"],
            name=op.f("fk_wallet_entries_promotion_id_promotions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["ride_id"],
            ["rides.id"],
            name=op.f("fk_wallet_entries_ride_id_rides"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
            name=op.f("fk_wallet_entries_wallet_id_wallets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallet_entries")),
    )
    op.create_index(
        "ix_wallet_entries_wallet_created",
        "wallet_entries",
        ["wallet_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_wallet_entries_kind_ride",
        "wallet_entries",
        ["kind", "ride_id"],
        unique=True,
        postgresql_where=sa.text("ride_id IS NOT NULL"),
    )
    op.add_column("rides", sa.Column("promotion_id", sa.Uuid(), nullable=True))
    op.add_column(
        "rides",
        sa.Column(
            "discount",
            sa.Numeric(precision=10, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.add_column("rides", sa.Column("rate_bcv", sa.Numeric(precision=14, scale=4), nullable=True))
    op.add_column(
        "rides", sa.Column("rate_binance", sa.Numeric(precision=14, scale=4), nullable=True)
    )
    op.create_index(op.f("ix_rides_promotion_id"), "rides", ["promotion_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_rides_promotion_id_promotions"),
        "rides",
        "promotions",
        ["promotion_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_rides_promotion_id_promotions"), "rides", type_="foreignkey")
    op.drop_index(op.f("ix_rides_promotion_id"), table_name="rides")
    op.drop_column("rides", "rate_binance")
    op.drop_column("rides", "rate_bcv")
    op.drop_column("rides", "discount")
    op.drop_column("rides", "promotion_id")
    op.drop_index(
        "uq_wallet_entries_kind_ride",
        table_name="wallet_entries",
        postgresql_where=sa.text("ride_id IS NOT NULL"),
    )
    op.drop_index("ix_wallet_entries_wallet_created", table_name="wallet_entries")
    op.drop_table("wallet_entries")
    op.drop_table("wallets")
    op.drop_index(
        "uq_promotions_code", table_name="promotions", postgresql_where=sa.text("code IS NOT NULL")
    )
    op.drop_table("promotions")
    op.drop_index("ix_exchange_rates_source_fetched", table_name="exchange_rates")
    op.drop_table("exchange_rates")
    # ### end Alembic commands ###
    for name in ("wallet_entry_kind", "discount_type", "rate_origin", "rate_source"):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
