"""add reports and suspensions

Revision ID: 59ad7c9a9b21
Revises: a1635064cfed
Create Date: 2026-10-09 22:13:18.381402+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "59ad7c9a9b21"
down_revision: Union[str, Sequence[str], None] = "a1635064cfed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("reporter_id", sa.Uuid(), nullable=False),
        sa.Column("reported_user_id", sa.Uuid(), nullable=True),
        sa.Column("ride_id", sa.Uuid(), nullable=True),
        sa.Column(
            "reporter_role", sa.Enum("passenger", "driver", name="reporter_role"), nullable=True
        ),
        sa.Column(
            "category",
            sa.Enum(
                "safety",
                "harassment",
                "driving",
                "fare",
                "vehicle_mismatch",
                "lost_item",
                "no_show",
                "app_issue",
                "other",
                name="report_category",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "in_review", "resolved", "dismissed", name="report_status"),
            nullable=False,
        ),
        sa.Column("priority", sa.Enum("normal", "urgent", name="report_priority"), nullable=False),
        sa.Column("assigned_to_id", sa.Uuid(), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to_id"],
            ["users.id"],
            name=op.f("fk_reports_assigned_to_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reported_user_id"],
            ["users.id"],
            name=op.f("fk_reports_reported_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["users.id"],
            name=op.f("fk_reports_reporter_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_id"],
            ["users.id"],
            name=op.f("fk_reports_resolved_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["ride_id"], ["rides.id"], name=op.f("fk_reports_ride_id_rides"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(
        op.f("ix_reports_reported_user_id"), "reports", ["reported_user_id"], unique=False
    )
    op.create_index(op.f("ix_reports_reporter_id"), "reports", ["reporter_id"], unique=False)
    op.create_index(op.f("ix_reports_ride_id"), "reports", ["ride_id"], unique=False)
    op.create_index("ix_reports_status_created", "reports", ["status", "created_at"], unique=False)
    op.create_index(
        "uq_reports_open_ride_reporter",
        "reports",
        ["ride_id", "reporter_id"],
        unique=True,
        postgresql_where=sa.text("ride_id IS NOT NULL AND status IN ('open', 'in_review')"),
    )
    op.create_table(
        "report_notes",
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind", sa.Enum("note", "status", "suspension", name="report_note_kind"), nullable=False
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_report_notes_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
            name=op.f("fk_report_notes_report_id_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_notes")),
    )
    op.create_index(op.f("ix_report_notes_report_id"), "report_notes", ["report_id"], unique=False)
    op.create_table(
        "suspensions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("report_id", sa.Uuid(), nullable=True),
        sa.Column("lifted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lifted_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_suspensions_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["lifted_by_id"],
            ["users.id"],
            name=op.f("fk_suspensions_lifted_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
            name=op.f("fk_suspensions_report_id_reports"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_suspensions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suspensions")),
    )
    op.create_index(
        "ix_suspensions_user_lifted", "suspensions", ["user_id", "lifted_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_suspensions_user_lifted", table_name="suspensions")
    op.drop_table("suspensions")
    op.drop_index(op.f("ix_report_notes_report_id"), table_name="report_notes")
    op.drop_table("report_notes")
    op.drop_index(
        "uq_reports_open_ride_reporter",
        table_name="reports",
        postgresql_where=sa.text("ride_id IS NOT NULL AND status IN ('open', 'in_review')"),
    )
    op.drop_index("ix_reports_status_created", table_name="reports")
    op.drop_index(op.f("ix_reports_ride_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_reporter_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_reported_user_id"), table_name="reports")
    op.drop_table("reports")
    for name in (
        "report_note_kind",
        "report_priority",
        "report_status",
        "report_category",
        "reporter_role",
    ):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
