"""add rides

Revision ID: a6c070a172af
Revises: d58536282b54
Create Date: 2026-10-09 18:48:10.391433+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a6c070a172af"
down_revision: Union[str, Sequence[str], None] = "d58536282b54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rides",
        sa.Column("passenger_id", sa.Uuid(), nullable=False),
        sa.Column("driver_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "searching",
                "driver_assigned",
                "driver_arrived",
                "in_progress",
                "completed",
                "cancelled_by_passenger",
                "cancelled_by_driver",
                "cancelled_by_admin",
                "no_drivers",
                name="ride_status",
            ),
            nullable=False,
        ),
        # vehicle_type already exists (drivers migration): reuse it, do not create it again.
        sa.Column(
            "vehicle_type",
            postgresql.ENUM("moto", "car", name="vehicle_type", create_type=False),
            nullable=False,
        ),
        sa.Column("pickup_lat", sa.Float(), nullable=False),
        sa.Column("pickup_lng", sa.Float(), nullable=False),
        sa.Column("pickup_address", sa.String(length=300), nullable=False),
        sa.Column("dropoff_lat", sa.Float(), nullable=False),
        sa.Column("dropoff_lng", sa.Float(), nullable=False),
        sa.Column("dropoff_address", sa.String(length=300), nullable=False),
        sa.Column("distance_m", sa.Integer(), nullable=False),
        sa.Column("duration_s", sa.Integer(), nullable=False),
        sa.Column("fare", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("surge_multiplier", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column(
            "payment_method",
            sa.Enum(
                "cash_usd", "pago_movil", "binance", "zelle", "cash_ves", name="payment_method"
            ),
            nullable=False,
        ),
        sa.Column("polyline", sa.Text(), nullable=True),
        sa.Column("vehicle", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("search_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("arrived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("cancelled_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "rated_by_passenger", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("rated_by_driver", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_by_id"],
            ["users.id"],
            name=op.f("fk_rides_cancelled_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"], ["users.id"], name=op.f("fk_rides_driver_id_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["passenger_id"],
            ["users.id"],
            name=op.f("fk_rides_passenger_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rides")),
    )
    op.create_index("ix_rides_driver_status", "rides", ["driver_id", "status"], unique=False)
    op.create_index("ix_rides_passenger_status", "rides", ["passenger_id", "status"], unique=False)
    op.create_index(op.f("ix_rides_requested_at"), "rides", ["requested_at"], unique=False)
    op.create_index(op.f("ix_rides_status"), "rides", ["status"], unique=False)
    op.create_index(
        "uq_rides_active_driver",
        "rides",
        ["driver_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('driver_arrived', 'driver_assigned', 'in_progress')"),
    )
    op.create_index(
        "uq_rides_active_passenger",
        "rides",
        ["passenger_id"],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('driver_arrived', 'driver_assigned', 'in_progress', 'searching')"
        ),
    )
    op.create_table(
        "ratings",
        sa.Column("ride_id", sa.Uuid(), nullable=False),
        sa.Column("rater_id", sa.Uuid(), nullable=False),
        sa.Column("ratee_id", sa.Uuid(), nullable=False),
        sa.Column("rater_role", sa.Enum("passenger", "driver", name="rating_role"), nullable=False),
        sa.Column("stars", sa.SmallInteger(), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("stars BETWEEN 1 AND 5", name=op.f("ck_ratings_stars_range")),
        sa.ForeignKeyConstraint(
            ["ratee_id"], ["users.id"], name=op.f("fk_ratings_ratee_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["rater_id"], ["users.id"], name=op.f("fk_ratings_rater_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["ride_id"], ["rides.id"], name=op.f("fk_ratings_ride_id_rides"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ratings")),
        sa.UniqueConstraint("ride_id", "rater_id", name=op.f("uq_ratings_ride_id")),
    )
    op.create_index(op.f("ix_ratings_ratee_id"), "ratings", ["ratee_id"], unique=False)
    op.create_index(op.f("ix_ratings_ride_id"), "ratings", ["ride_id"], unique=False)
    op.create_table(
        "ride_messages",
        sa.Column("ride_id", sa.Uuid(), nullable=False),
        sa.Column("sender_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ride_id"],
            ["rides.id"],
            name=op.f("fk_ride_messages_ride_id_rides"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
            name=op.f("fk_ride_messages_sender_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ride_messages")),
    )
    op.create_index(
        "ix_ride_messages_ride_created", "ride_messages", ["ride_id", "created_at"], unique=False
    )
    op.create_table(
        "ride_offers",
        sa.Column("ride_id", sa.Uuid(), nullable=False),
        sa.Column("driver_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "accepted", "declined", "expired", "cancelled", name="ride_offer_status"
            ),
            nullable=False,
        ),
        sa.Column("pickup_distance_m", sa.Integer(), nullable=False),
        sa.Column("pickup_eta_s", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["users.id"],
            name=op.f("fk_ride_offers_driver_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ride_id"], ["rides.id"], name=op.f("fk_ride_offers_ride_id_rides"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ride_offers")),
        sa.UniqueConstraint("ride_id", "driver_id", name=op.f("uq_ride_offers_ride_id")),
    )
    op.create_index(
        "ix_ride_offers_driver_status", "ride_offers", ["driver_id", "status"], unique=False
    )
    op.create_index(op.f("ix_ride_offers_ride_id"), "ride_offers", ["ride_id"], unique=False)
    op.add_column(
        "driver_profiles",
        sa.Column("rating_sum", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column(
        "driver_profiles",
        sa.Column("rating_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column(
        "driver_profiles", sa.Column("rating_avg", sa.Numeric(precision=3, scale=2), nullable=True)
    )
    op.add_column(
        "users", sa.Column("rating_sum", sa.Integer(), server_default=sa.text("0"), nullable=False)
    )
    op.add_column(
        "users",
        sa.Column("rating_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column("users", sa.Column("rating_avg", sa.Numeric(precision=3, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "rating_avg")
    op.drop_column("users", "rating_count")
    op.drop_column("users", "rating_sum")
    op.drop_column("driver_profiles", "rating_avg")
    op.drop_column("driver_profiles", "rating_count")
    op.drop_column("driver_profiles", "rating_sum")
    op.drop_index(op.f("ix_ride_offers_ride_id"), table_name="ride_offers")
    op.drop_index("ix_ride_offers_driver_status", table_name="ride_offers")
    op.drop_table("ride_offers")
    op.drop_index("ix_ride_messages_ride_created", table_name="ride_messages")
    op.drop_table("ride_messages")
    op.drop_index(op.f("ix_ratings_ride_id"), table_name="ratings")
    op.drop_index(op.f("ix_ratings_ratee_id"), table_name="ratings")
    op.drop_table("ratings")
    op.drop_index(
        "uq_rides_active_passenger",
        table_name="rides",
        postgresql_where=sa.text(
            "status IN ('driver_arrived', 'driver_assigned', 'in_progress', 'searching')"
        ),
    )
    op.drop_index(
        "uq_rides_active_driver",
        table_name="rides",
        postgresql_where=sa.text("status IN ('driver_arrived', 'driver_assigned', 'in_progress')"),
    )
    op.drop_index(op.f("ix_rides_status"), table_name="rides")
    op.drop_index(op.f("ix_rides_requested_at"), table_name="rides")
    op.drop_index("ix_rides_passenger_status", table_name="rides")
    op.drop_index("ix_rides_driver_status", table_name="rides")
    op.drop_table("rides")
    # vehicle_type belongs to the drivers migration and is kept.
    for name in ("rating_role", "ride_offer_status", "payment_method", "ride_status"):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
